version: '3.8'

services:
  backend:
    build:
      context: ./engine
    ports:
      - "5001:5000"
    env_file:
      - ./engine/.env
    restart: always

  frontend:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
